//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTrans.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UATEntities : DbContext
    {
        public UATEntities()
            : base("name=UATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<Org_User> Org_User { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<User_Contact> User_Contact { get; set; }
        public virtual DbSet<User_Child> User_Child { get; set; }
        public virtual DbSet<Child> Children { get; set; }
        public virtual DbSet<Child_Condition> Child_Condition { get; set; }
        public virtual DbSet<Child_Contact> Child_Contact { get; set; }
    }
}
