//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTrans.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Org_User = new HashSet<Org_User>();
            this.User_Contact = new HashSet<User_Contact>();
            this.User_Child = new HashSet<User_Child>();
        }
    
        public int Id { get; set; }
        public Nullable<long> EwayCustomerId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public Nullable<int> ContactId { get; set; }
        public int RoleId { get; set; }
        public string Password { get; set; }
        public string PasswordHash { get; set; }
        public bool CanLogin { get; set; }
        public string EmailConfirmationToken { get; set; }
        public Nullable<bool> IsEmailConfirmationValid { get; set; }
        public string PasswordResetToken { get; set; }
        public Nullable<bool> IsPswResetTokenValid { get; set; }
        public bool IsAdmin { get; set; }
        public Nullable<System.DateTime> StaffPayrollLatSyncOn { get; set; }
        public Nullable<decimal> StaffCostPerHour { get; set; }
        public Nullable<int> TotalHoursToBeSync { get; set; }
        public string Colour { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public bool IsActive { get; set; }
        public byte[] Version { get; set; }
        public string PinCode { get; set; }
        public bool IsOrgAdmin { get; set; }
        public Nullable<System.DateTime> WorkStartDate { get; set; }
        public Nullable<System.DateTime> WorkEndDate { get; set; }
        public Nullable<int> CurrentOrgId { get; set; }
        public Nullable<System.DateTime> LastLogedOn { get; set; }
        public Nullable<int> RetryAttempt { get; set; }
        public bool SysAdmin { get; set; }
        public string Title { get; set; }
        public string PasswordBackup { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<bool> QuickRegistered { get; set; }
        public Nullable<bool> RequiredPasswordChange { get; set; }
        public Nullable<bool> IsKPFClient { get; set; }
        public Nullable<bool> IsAimyClient { get; set; }
        public Nullable<bool> IsIncompleteProfile { get; set; }
        public Nullable<bool> ShowFavourites { get; set; }
        public string TimeZoneIdentifier { get; set; }
        public string Culture { get; set; }
        public string Language { get; set; }
        public string ImportReference { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Lookup Lookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_User> Org_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Contact> User_Contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Child> User_Child { get; set; }
    }
}
